package confloder

import (
	"encoding/json"
	"errors"
	"log"
	"reflect"
	"runtime/debug"
	"sync"
	"time"

	"github.com/golang/groupcache/singleflight"
)

// LoadFunc 加载配置方法
// 包调用Init方法之后，会异步按照指定时间间隔调用此方法获取最新的配置数据
// 获取到配置数据后，若interface{}实现了MD5()string方法，会依据实现的方法计算MD5值，
// 否则对配置数据json序列化后取MD5值，最新MD5和缓存内的MD5值不同时，触发更新操作
type LoadFunc func() (interface{}, error)

// OnUpdateFunc 配置首次加载或更新时触发，配置数据预处理
type OnUpdateFunc func(interface{}) (interface{}, error)

// IMD5 if config struct implement MD5()string function,
// md5 value will be generated by implement
type IMD5 interface {
	MD5() string
}

// nsLoader 配置加载器
type nsLoader struct {
	// loader 配置获取函数
	loader LoadFunc
	// onUpdateFunc 配置更新时链式调用方法
	onUpdateFunc []OnUpdateFunc
}

type Manager struct {
	// duration 配置更新间隔，默认每分钟刷新一次
	duration time.Duration

	// cache 配置信息
	cache sync.Map
	group singleflight.Group

	lock     sync.RWMutex
	nsLoader map[string]nsLoader
}

type cacheItem struct {
	MD5        string
	Namespace  string
	ConfigData reflect.Value
}

var configM = &Manager{
	nsLoader: make(map[string]nsLoader, 1<<3),
	duration: time.Minute, // 默认每分钟刷新一次配置
}

type Option func(*Manager)

func WithPollingDuration(duration time.Duration) Option {
	return func(m *Manager) {
		m.duration = duration
	}
}

func InitConfigManager(opts ...Option) {
	for _, opt := range opts {
		opt(configM)
	}
	go configM.pollingConfig()
}

func (cm *Manager) pollingConfig() {
	if cm.duration == 0 {
		return
	}
	defer func() {
		if err := recover(); err != nil {
			log.Println("polling config panic:", string(debug.Stack()))
		}
	}()
	ticker := time.NewTicker(cm.duration)
	for {
		select {
		case <-ticker.C:
			nsList := cm.getAllNamespace()
			for _, ns := range nsList {
				loadFunc, ok := cm.getNsLoader(ns)
				if !ok {
					continue
				}
				_ = configM.loadNamespaceConfig(ns, loadFunc)
			}
		}
	}
}

func (cm *Manager) registerLoadFunc(ns string, loadFunc LoadFunc, onUpdateFunc ...OnUpdateFunc) {
	cm.lock.Lock()
	defer cm.lock.Unlock()
	cm.nsLoader[ns] = nsLoader{loader: loadFunc, onUpdateFunc: onUpdateFunc}
}

func (cm *Manager) getNsLoader(ns string) (nsLoader, bool) {
	cm.lock.RLock()
	defer cm.lock.RUnlock()
	loader, ok := cm.nsLoader[ns]
	return loader, ok
}

func (cm *Manager) getAllNamespace() []string {
	cm.lock.RLock()
	defer cm.lock.RUnlock()
	nsList := make([]string, 0, len(cm.nsLoader))
	for ns := range cm.nsLoader {
		nsList = append(nsList, ns)
	}
	return nsList
}

func (cm *Manager) loadNamespaceConfig(ns string, loader nsLoader) error {
	_, err := cm.group.Do(ns, func() (interface{}, error) {
		configData, err := loader.loader()
		if err != nil {
			return nil, err
		}
		cacheInfo := new(cacheItem)
		implMD5Func, ok := configData.(IMD5)
		if ok {
			cacheInfo.MD5 = implMD5Func.MD5()
		} else {
			seqData, err := json.Marshal(configData)
			if err != nil {
				return nil, err
			}
			cacheInfo.MD5 = BytesMD5(seqData)
		}

		// 获取原配置信息，判断配置是否发生变更
		oldCacheInfo, ok := configM.cache.Load(ns)
		if ok && oldCacheInfo.(*cacheItem).MD5 == cacheInfo.MD5 { // 配置无更新，直接返回
			return nil, nil
		}
		for _, onUpdateFunc := range loader.onUpdateFunc {
			configData, err = onUpdateFunc(configData)
			if err != nil {
				return nil, err
			}
		}
		cacheInfo.Namespace = ns
		cacheInfo.ConfigData = reflect.ValueOf(configData)
		configM.cache.Store(ns, cacheInfo)
		return configData, nil
	})
	return err
}

func (cm *Manager) getCacheItem(ns string) (*cacheItem, error) {
	cacheInfo, ok := configM.cache.Load(ns)
	if !ok {
		var loader nsLoader
		loader, ok = configM.getNsLoader(ns)
		if !ok {
			return nil, errors.New("not config namespace load function")
		}
		err := configM.loadNamespaceConfig(ns, loader)
		if err != nil {
			return nil, err
		}
		cacheInfo, ok = configM.cache.Load(ns)
	}
	if !ok {
		return nil, errors.New("config data not in cache, please check load function")
	}
	nsConfig, ok := cacheInfo.(*cacheItem)
	if !ok {
		return nil, errors.New("inner error: namespace config assert error")
	}
	return nsConfig, nil
}

func GetMD5(ns string) string {
	cacheIns, err := configM.getCacheItem(ns)
	if err != nil {
		return ""
	}
	return cacheIns.MD5
}

func GetConfigData(ns string) (interface{}, error) {
	cacheIns, err := configM.getCacheItem(ns)
	if err != nil {
		return nil, err
	}
	return cacheIns.ConfigData.Interface(), nil
}

func RegisterNamespaceConfig(ns string, getter LoadFunc, updateFunc ...OnUpdateFunc) {
	configM.registerLoadFunc(ns, getter, updateFunc...)
}

func LoadConfig(nsList ...string) {
	for _, ns := range nsList {
		getFunc, ok := configM.getNsLoader(ns)
		if !ok {
			continue
		}
		_ = configM.loadNamespaceConfig(ns, getFunc)
	}
}

// LoadAllConfig 只会加载在调用此方法前注册的namespace
func LoadAllConfig() {
	LoadConfig(configM.getAllNamespace()...)
}
